name = "paper-sniffer-frontend"
main = "src/worker.ts"
compatibility_date = "2026-05-14"
workers_dev = true

[vars]
APP_TITLE = "PaperSniffer"

[dev]
port = 8788

[[services]]
binding = "BACKEND"
service = "paper-sniffer-backend"