#!/usr/bin/env bash
# Local/cloud deployment helper for the PaperSniffer frontend Worker.
#
# Usage:
#   BACKEND_BASE_URL=http://127.0.0.1:8787 BACKEND_ADMIN_TOKEN=... bash frontend/script/deploy.sh local
#   BACKEND_BASE_URL=https://paper-sniffer-backend.<subdomain>.workers.dev BACKEND_ADMIN_TOKEN=... bash frontend/script/deploy.sh cloud

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CONFIG_DIR="$ROOT/frontend/script/config"
SRC_VARS="$CONFIG_DIR/.dev.vars"
WRANGLER_CONFIG="$ROOT/frontend/wrangler.toml"

REQUIRED_VARS=(
  BACKEND_BASE_URL
  BACKEND_ADMIN_TOKEN
)

OPTIONAL_VARS=(
  FRONTEND_PASSWORD
  SESSION_SECRET
  APP_TITLE
)

usage() {
  cat >&2 <<'EOF'
Usage:
  BACKEND_BASE_URL=<backend-url> BACKEND_ADMIN_TOKEN=<token> bash frontend/script/deploy.sh <local|cloud>

Optional:
  FRONTEND_PASSWORD=<password>
  SESSION_SECRET=<session-signing-secret>
  APP_TITLE=PaperSniffer
EOF
  exit 1
}

MODE="${1:-}"
[[ "$MODE" =~ ^(local|cloud)$ ]] || usage

require_env_vars() {
  local missing=()

  for key in "${REQUIRED_VARS[@]}"; do
    if [[ -z "${!key+x}" ]] || [[ -z "${!key}" ]]; then
      missing+=("$key")
    fi
  done

  if (( ${#missing[@]} > 0 )); then
    echo "Error: missing required shell environment variable(s): ${missing[*]}" >&2
    usage
  fi
}

write_var_line() {
  local key="$1"
  local value="$2"
  local file="$3"

  if [[ "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
    echo "Error: $key contains a newline; pass it as a single-line value." >&2
    exit 1
  fi

  if [[ "$value" =~ [[:space:]#] ]]; then
    local escaped="$value"
    escaped="${escaped//\\/\\\\}"
    escaped="${escaped//\"/\\\"}"
    printf '%s="%s"\n' "$key" "$escaped" >> "$file"
  else
    printf '%s=%s\n' "$key" "$value" >> "$file"
  fi
}

generate_dev_vars() {
  mkdir -p "$CONFIG_DIR"

  local tmp
  tmp="$(mktemp "$CONFIG_DIR/.dev.vars.tmp.XXXXXX")"
  chmod 600 "$tmp" 2>/dev/null || true

  {
    echo "# Generated by frontend/script/deploy.sh from shell environment variables."
    echo "# Do not edit this file manually; rerun deploy.sh with updated variables."
  } > "$tmp"

  for key in "${REQUIRED_VARS[@]}"; do
    write_var_line "$key" "${!key}" "$tmp"
  done

  for key in "${OPTIONAL_VARS[@]}"; do
    if [[ -n "${!key+x}" ]] && [[ -n "${!key}" ]]; then
      write_var_line "$key" "${!key}" "$tmp"
    fi
  done

  mv "$tmp" "$SRC_VARS"
  echo "==> Generated $SRC_VARS"
}

require_env_vars
generate_dev_vars

cd "$ROOT"
npm run typecheck:frontend
npm run build:frontend

case "$MODE" in
  local)
    echo "==> Starting local frontend Worker on http://127.0.0.1:8788"
    exec npx wrangler dev --config "$WRANGLER_CONFIG" --local --env-file "$SRC_VARS"
    ;;
  cloud)
    echo "==> Deploying frontend Worker to Cloudflare"
    exec npx wrangler deploy --config "$WRANGLER_CONFIG" --secrets-file "$SRC_VARS"
    ;;
esac
