#!/usr/bin/env bash
# Local/cloud deployment helper.
#
# Important:
#   backend/script/config/.dev.vars is generated from shell
#   environment variables on every run. It is not used as input.
#
# Usage:
#   OPENAI_API_KEY=sk-... ADMIN_TOKEN=... bash backend/script/deploy.sh local
#   OPENAI_API_KEY=sk-... ADMIN_TOKEN=... bash backend/script/deploy.sh cloud
#
# PowerShell:
#   $env:OPENAI_API_KEY="sk-..."
#   $env:ADMIN_TOKEN="..."
#   npm.cmd run deploy:local

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CONFIG_DIR="$ROOT/backend/script/config"
SRC_VARS="$CONFIG_DIR/.dev.vars"
WRANGLER_CONFIG="$ROOT/backend/wrangler.toml"
KV_BINDING="CONFIG_KV"
D1_BINDING="PAPER_DB"
D1_DATABASE_NAME="paper-sniffer-db"
QUEUE_NAME="paper-sniffer-analysis"

REQUIRED_VARS=(
  OPENAI_API_KEY
  ADMIN_TOKEN
)

usage() {
  cat >&2 <<'EOF'
Usage:
  OPENAI_API_KEY=sk-... ADMIN_TOKEN=... bash backend/script/deploy.sh <local|cloud>
EOF
  exit 1
}

MODE="${1:-}"
[[ "$MODE" =~ ^(local|cloud)$ ]] || usage

require_env_vars() {
  local missing=()

  for key in "${REQUIRED_VARS[@]}"; do
    if [[ -z "${!key+x}" ]] || [[ -z "${!key}" ]]; then
      missing+=("$key")
    fi
  done

  if (( ${#missing[@]} > 0 )); then
    echo "Error: missing required shell environment variable(s): ${missing[*]}" >&2
    echo "Pass them inline or export them before running this script." >&2
    echo "Example: OPENAI_API_KEY=sk-... ADMIN_TOKEN=... bash backend/script/deploy.sh $MODE" >&2
    exit 1
  fi
}

write_var_line() {
  local key="$1"
  local value="$2"
  local file="$3"

  if [[ "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
    echo "Error: $key contains a newline; pass it as a single-line value for .dev.vars." >&2
    exit 1
  fi

  if [[ "$value" =~ [[:space:]#] ]]; then
    local escaped="$value"
    escaped="${escaped//\\/\\\\}"
    escaped="${escaped//\"/\\\"}"
    printf '%s="%s"\n' "$key" "$escaped" >> "$file"
  else
    printf '%s=%s\n' "$key" "$value" >> "$file"
  fi
}

generate_dev_vars() {
  mkdir -p "$CONFIG_DIR"

  local tmp
  tmp="$(mktemp "$CONFIG_DIR/.dev.vars.tmp.XXXXXX")"
  chmod 600 "$tmp" 2>/dev/null || true

  {
    echo "# Generated by backend/script/deploy.sh from shell environment variables."
    echo "# Do not edit this file manually; rerun deploy.sh with updated variables."
  } > "$tmp"

  for key in "${REQUIRED_VARS[@]}"; do
    write_var_line "$key" "${!key}" "$tmp"
  done

  mv "$tmp" "$SRC_VARS"

  echo "==> Generated $SRC_VARS from shell environment variables"
}

toml_first_value() {
  local key="$1"
  sed -nE "s/^[[:space:]]*$key[[:space:]]*=[[:space:]]*\"([^\"]*)\".*/\\1/p" "$WRANGLER_CONFIG" | head -n 1
}

is_missing_or_placeholder() {
  local value="$1"
  [[ -z "$value" || "$value" == *your* || "$value" == *YOUR* || "$value" == *你的* || "$value" == *TODO* || "$value" == *CHANGE_ME* || "$value" == *"<"* || "$value" == *">"* ]]
}

ensure_cloudflare_auth() {
  echo "==> Checking Cloudflare login"
  if npx wrangler whoami --config "$WRANGLER_CONFIG" >/dev/null 2>&1; then
    npx wrangler whoami --config "$WRANGLER_CONFIG"
    return
  fi

  echo "==> Wrangler is not logged in; starting login flow"
  npx wrangler login
  npx wrangler whoami --config "$WRANGLER_CONFIG"
}

ensure_kv_namespace() {
  local kv_id
  kv_id="$(toml_first_value id)"

  if is_missing_or_placeholder "$kv_id"; then
    echo "==> Creating KV namespace $KV_BINDING and updating wrangler.toml"
    npx wrangler kv namespace create "$KV_BINDING" \
      --config "$WRANGLER_CONFIG" \
      --binding "$KV_BINDING" \
      --update-config
    return
  fi

  echo "==> KV namespace configured: $KV_BINDING ($kv_id)"
  npx wrangler kv namespace list --config "$WRANGLER_CONFIG" >/dev/null
}

ensure_queue() {
  local list_output
  list_output="$(mktemp)"

  echo "==> Checking Queue $QUEUE_NAME"
  npx wrangler queues list --config "$WRANGLER_CONFIG" > "$list_output"

  if grep -Fq "$QUEUE_NAME" "$list_output"; then
    echo "==> Queue exists: $QUEUE_NAME"
    rm -f "$list_output"
    return
  fi

  rm -f "$list_output"
  echo "==> Creating Queue $QUEUE_NAME"
  npx wrangler queues create "$QUEUE_NAME" --config "$WRANGLER_CONFIG"
}

ensure_d1_database() {
  local database_id
  database_id="$(toml_first_value database_id)"

  if is_missing_or_placeholder "$database_id"; then
    echo "==> Creating D1 database $D1_DATABASE_NAME and updating wrangler.toml"
    npx wrangler d1 create "$D1_DATABASE_NAME" \
      --config "$WRANGLER_CONFIG" \
      --binding "$D1_BINDING" \
      --update-config
    return
  fi

  echo "==> D1 database configured: $D1_DATABASE_NAME ($database_id)"
  npx wrangler d1 list --config "$WRANGLER_CONFIG" >/dev/null
}

ensure_cron_config() {
  echo "==> Checking Cron trigger config"
  if ! grep -Fq 'crons = ["0 1 * * *"]' "$WRANGLER_CONFIG"; then
    echo "Error: expected cron trigger was not found in $WRANGLER_CONFIG" >&2
    echo 'Expected: crons = ["0 1 * * *"]' >&2
    exit 1
  fi
}

ensure_cloud_resources() {
  ensure_cloudflare_auth
  ensure_kv_namespace
  ensure_queue
  ensure_d1_database
  ensure_cron_config
}

deploy_cloud() {
  echo "==> Deploying to Cloudflare with generated secrets file"
  npx wrangler deploy --config "$WRANGLER_CONFIG" --secrets-file "$SRC_VARS"
}

require_env_vars
generate_dev_vars

cd "$ROOT"
npm run typecheck
npm run build

case "$MODE" in
  local)
    echo "==> Starting local Worker (--local)"
    exec npx wrangler dev --config "$WRANGLER_CONFIG" --local --env-file "$SRC_VARS"
    ;;
  cloud)
    ensure_cloud_resources
    deploy_cloud
    ;;
esac
