param(
  [switch]$Help
)

$ErrorActionPreference = "Stop"

function Show-Usage {
  @"
Usage:
  `$env:OPENAI_API_KEY="sk-..."
  `$env:ADMIN_TOKEN="local-dev-token"
  npm.cmd run local:build-run

Environment knobs:
  BACKEND_PORT=8787
  FRONTEND_PORT=8788
  FRONTEND_PASSWORD=<optional UI password>
  SESSION_SECRET=<optional cookie signing secret>
  KEEP_ALIVE=true|false
  RUN_FULL_API_TESTS=true|false
"@ | Write-Host
}

if ($Help) {
  Show-Usage
  exit 0
}

$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
$BackendVars = Join-Path $Root "backend/script/config/.dev.vars"
$FrontendVars = Join-Path $Root "frontend/script/config/.dev.vars"
$BackendConfig = Join-Path $Root "backend/wrangler.toml"
$FrontendConfig = Join-Path $Root "frontend/wrangler.toml"
$BackendPort = if ($env:BACKEND_PORT) { $env:BACKEND_PORT } else { "8787" }
$FrontendPort = if ($env:FRONTEND_PORT) { $env:FRONTEND_PORT } else { "8788" }
$BackendBaseUrl = "http://127.0.0.1:$BackendPort"
$FrontendBaseUrl = "http://127.0.0.1:$FrontendPort"
$KeepAlive = if ($env:KEEP_ALIVE) { $env:KEEP_ALIVE } else { "true" }
$RunFullApiTests = if ($env:RUN_FULL_API_TESTS) { $env:RUN_FULL_API_TESTS } else { "false" }
$AppTitle = if ($env:APP_TITLE) { $env:APP_TITLE } else { "PaperSniffer" }
$LogDir = Join-Path $Root "script/.local-build-run"
$CookieJar = Join-Path $LogDir "cookies.txt"

$BackendWorker = $null
$FrontendWorker = $null

function Load-ExistingVars {
  param([string]$Path)

  if (!(Test-Path -LiteralPath $Path)) {
    return
  }

  foreach ($line in Get-Content -LiteralPath $Path) {
    if ($line -match '^\s*$' -or $line -match '^\s*#') {
      continue
    }

    if ($line -notmatch '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$') {
      continue
    }

    $key = $Matches[1]
    $value = $Matches[2].Trim()
    if ($value.Length -ge 2 -and $value.StartsWith('"') -and $value.EndsWith('"')) {
      $value = $value.Substring(1, $value.Length - 2)
      $value = $value.Replace('\"', '"').Replace('\\', '\')
    }

    if (![Environment]::GetEnvironmentVariable($key, "Process")) {
      [Environment]::SetEnvironmentVariable($key, $value, "Process")
    }
  }
}

function Require-Command {
  param([string]$Name)

  if (!(Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "Missing required command: $Name"
  }
}

function Require-Env {
  $missing = @()
  foreach ($key in @("OPENAI_API_KEY", "ADMIN_TOKEN")) {
    if (![Environment]::GetEnvironmentVariable($key, "Process")) {
      $missing += $key
    }
  }

  if ($missing.Count -gt 0) {
    Show-Usage
    throw "Missing required environment variable(s): $($missing -join ', ')"
  }
}

function Format-DevVar {
  param(
    [string]$Key,
    [string]$Value
  )

  if ($Value -match "[`r`n]") {
    throw "$Key contains a newline; pass it as a single-line value."
  }

  if ($Value -match "\s|#") {
    $escaped = $Value.Replace('\', '\\').Replace('"', '\"')
    return "$Key=""$escaped"""
  }

  return "$Key=$Value"
}

function Write-Utf8NoBomLines {
  param(
    [string]$Path,
    [string[]]$Lines
  )

  $directory = Split-Path -Parent $Path
  New-Item -ItemType Directory -Force -Path $directory | Out-Null
  $encoding = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllLines($Path, $Lines, $encoding)
}

function Write-DevVars {
  $backendLines = @(
    "# Generated by script/local-build-run.ps1.",
    "# Do not edit this file manually; rerun the script with updated environment variables.",
    (Format-DevVar "OPENAI_API_KEY" $env:OPENAI_API_KEY),
    (Format-DevVar "ADMIN_TOKEN" $env:ADMIN_TOKEN)
  )
  Write-Utf8NoBomLines $BackendVars $backendLines

  $frontendLines = @(
    "# Generated by script/local-build-run.ps1.",
    "# Do not edit this file manually; rerun the script with updated environment variables.",
    (Format-DevVar "BACKEND_BASE_URL" $BackendBaseUrl),
    (Format-DevVar "BACKEND_ADMIN_TOKEN" $env:ADMIN_TOKEN),
    (Format-DevVar "APP_TITLE" $AppTitle)
  )

  if ($env:FRONTEND_PASSWORD) {
    $frontendLines += Format-DevVar "FRONTEND_PASSWORD" $env:FRONTEND_PASSWORD
  }

  if ($env:SESSION_SECRET) {
    $frontendLines += Format-DevVar "SESSION_SECRET" $env:SESSION_SECRET
  }

  Write-Utf8NoBomLines $FrontendVars $frontendLines

  Write-Host "==> Wrote backend env: $BackendVars"
  Write-Host "==> Wrote frontend env: $FrontendVars"
}

function Invoke-Step {
  param(
    [string]$Name,
    [string]$FilePath,
    [string[]]$Arguments
  )

  Write-Host "==> $Name"
  & $FilePath @Arguments
  if ($LASTEXITCODE -ne 0) {
    throw "$Name failed with exit code $LASTEXITCODE"
  }
}

function Start-Worker {
  param(
    [string]$Name,
    [string]$Config,
    [string]$EnvFile,
    [string]$Port
  )

  $stdout = Join-Path $LogDir "$Name.out.log"
  $stderr = Join-Path $LogDir "$Name.err.log"
  $arguments = @(
    "wrangler",
    "dev",
    "--config",
    $Config,
    "--local",
    "--env-file",
    $EnvFile,
    "--port",
    $Port
  )

  Write-Host "==> Starting $Name Worker"
  $process = Start-Process `
    -FilePath "npx.cmd" `
    -ArgumentList $arguments `
    -RedirectStandardOutput $stdout `
    -RedirectStandardError $stderr `
    -WindowStyle Hidden `
    -PassThru

  [pscustomobject]@{
    Name = $Name
    Process = $process
    Stdout = $stdout
    Stderr = $stderr
  }
}

function Show-LogTail {
  param($Worker)

  Write-Host "---- $($Worker.Name) stdout ----"
  if (Test-Path -LiteralPath $Worker.Stdout) {
    Get-Content -LiteralPath $Worker.Stdout -Tail 80
  } else {
    Write-Host "<empty>"
  }

  Write-Host "---- $($Worker.Name) stderr ----"
  if (Test-Path -LiteralPath $Worker.Stderr) {
    Get-Content -LiteralPath $Worker.Stderr -Tail 80
  } else {
    Write-Host "<empty>"
  }
}

function Stop-Worker {
  param($Worker)

  if ($null -eq $Worker) {
    return
  }

  $Worker.Process.Refresh()
  if (!$Worker.Process.HasExited) {
    Stop-Process -Id $Worker.Process.Id -Force -ErrorAction SilentlyContinue
  }
}

function Get-HttpStatus {
  param([string[]]$CurlArgs)

  $bodyFile = Join-Path $LogDir ("response-{0}.txt" -f ([Guid]::NewGuid().ToString("N")))
  $status = & curl.exe `
    --silent `
    --show-error `
    --connect-timeout 5 `
    --max-time 30 `
    --output $bodyFile `
    --write-out "%{http_code}" `
    @CurlArgs 2>$null

  [pscustomobject]@{
    Status = "$status".Trim()
    BodyFile = $bodyFile
  }
}

function Assert-Http {
  param(
    [string]$Name,
    [string]$ExpectedStatus,
    [string[]]$CurlArgs
  )

  $result = Get-HttpStatus $CurlArgs
  if ($result.Status -ne $ExpectedStatus) {
    Write-Host "FAIL ${Name}: expected HTTP $ExpectedStatus, got $($result.Status)"
    if (Test-Path -LiteralPath $result.BodyFile) {
      Get-Content -LiteralPath $result.BodyFile | ForEach-Object { Write-Host "  $_" }
    }
    throw "$Name failed"
  }

  Write-Host "PASS $Name -> $($result.Status)"
}

function Wait-ForBackend {
  Write-Host "==> Waiting for backend at $BackendBaseUrl"

  for ($i = 0; $i -lt 90; $i += 1) {
    $result = Get-HttpStatus @(
      "--header",
      "Authorization: Bearer $env:ADMIN_TOKEN",
      "$BackendBaseUrl/health"
    )

    if ($result.Status -eq "200") {
      Write-Host "==> Backend is ready"
      return
    }

    $BackendWorker.Process.Refresh()
    if ($BackendWorker.Process.HasExited) {
      Show-LogTail $BackendWorker
      throw "Backend Worker exited before becoming ready."
    }

    Start-Sleep -Seconds 1
  }

  Show-LogTail $BackendWorker
  throw "Backend did not become ready in time."
}

function Wait-ForFrontend {
  Write-Host "==> Waiting for frontend at $FrontendBaseUrl"

  $path = if ($env:FRONTEND_PASSWORD) { "/login" } else { "/status" }
  for ($i = 0; $i -lt 90; $i += 1) {
    $result = Get-HttpStatus @("$FrontendBaseUrl$path")

    if ($result.Status -eq "200") {
      Write-Host "==> Frontend is ready"
      return
    }

    $FrontendWorker.Process.Refresh()
    if ($FrontendWorker.Process.HasExited) {
      Show-LogTail $FrontendWorker
      throw "Frontend Worker exited before becoming ready."
    }

    Start-Sleep -Seconds 1
  }

  Show-LogTail $FrontendWorker
  throw "Frontend did not become ready in time."
}

function Login-FrontendIfNeeded {
  if (!$env:FRONTEND_PASSWORD) {
    return
  }

  Assert-Http `
    "frontend login" `
    "303" `
    @(
      "--request",
      "POST",
      "--cookie-jar",
      $CookieJar,
      "--data-urlencode",
      "password=$env:FRONTEND_PASSWORD",
      "$FrontendBaseUrl/login"
    )
}

function Run-LightSmokeTests {
  Write-Host "==> Running lightweight smoke checks"

  Assert-Http `
    "backend health" `
    "200" `
    @(
      "--header",
      "Authorization: Bearer $env:ADMIN_TOKEN",
      "$BackendBaseUrl/health"
    )

  Assert-Http `
    "backend config" `
    "200" `
    @(
      "--header",
      "Authorization: Bearer $env:ADMIN_TOKEN",
      "$BackendBaseUrl/api/config"
    )

  Login-FrontendIfNeeded

  $cookieArgs = @()
  if ($env:FRONTEND_PASSWORD) {
    $cookieArgs = @("--cookie", $CookieJar)
  }

  Assert-Http "frontend status page" "200" ($cookieArgs + @("$FrontendBaseUrl/status"))
  Assert-Http "frontend dashboard page" "200" ($cookieArgs + @("$FrontendBaseUrl/"))
  Assert-Http "frontend API proxy health" "200" ($cookieArgs + @("$FrontendBaseUrl/api/health"))
}

function Run-FullApiTestsIfRequested {
  if ($RunFullApiTests -ne "true") {
    return
  }

  if (!(Get-Command bash -ErrorAction SilentlyContinue)) {
    throw "RUN_FULL_API_TESTS=true requires bash because the existing smoke tests are bash scripts."
  }

  Write-Host "==> Running full API smoke tests"
  & bash (Join-Path $Root "backend/script/test.sh") local $BackendBaseUrl
  if ($LASTEXITCODE -ne 0) {
    throw "backend/script/test.sh failed"
  }

  & bash (Join-Path $Root "frontend/script/test.sh") local $FrontendBaseUrl
  if ($LASTEXITCODE -ne 0) {
    throw "frontend/script/test.sh failed"
  }
}

try {
  Load-ExistingVars $BackendVars
  Load-ExistingVars $FrontendVars
  Require-Command "npm.cmd"
  Require-Command "npx.cmd"
  Require-Command "curl.exe"
  Require-Env

  New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
  if (Test-Path -LiteralPath $CookieJar) {
    Remove-Item -LiteralPath $CookieJar -Force
  }

  Set-Location $Root

  Invoke-Step "Typechecking backend and frontend" "npm.cmd" @("run", "typecheck")
  Invoke-Step "Building backend and frontend" "npm.cmd" @("run", "build")
  Write-DevVars

  $BackendWorker = Start-Worker "backend" $BackendConfig $BackendVars $BackendPort
  Wait-ForBackend

  $FrontendWorker = Start-Worker "frontend" $FrontendConfig $FrontendVars $FrontendPort
  Wait-ForFrontend

  Run-LightSmokeTests
  Run-FullApiTestsIfRequested

  Write-Host "==> Local build-run pass completed"
  Write-Host "    Backend:  $BackendBaseUrl"
  Write-Host "    Frontend: $FrontendBaseUrl"
  Write-Host "    Logs:     $LogDir"

  if ($KeepAlive -ne "true") {
    Write-Host "==> KEEP_ALIVE=false, stopping local Workers"
    exit 0
  }

  Write-Host "==> Workers are still running. Press Ctrl+C to stop both."
  while ($true) {
    $BackendWorker.Process.Refresh()
    $FrontendWorker.Process.Refresh()

    if ($BackendWorker.Process.HasExited) {
      Show-LogTail $BackendWorker
      throw "Backend Worker exited."
    }

    if ($FrontendWorker.Process.HasExited) {
      Show-LogTail $FrontendWorker
      throw "Frontend Worker exited."
    }

    Start-Sleep -Seconds 2
  }
} finally {
  Stop-Worker $FrontendWorker
  Stop-Worker $BackendWorker
}
