#!/usr/bin/env bash
# Build and run the local backend + frontend Workers together.
#
# This script does a full local pass:
#   1. typecheck backend and frontend
#   2. build backend and frontend
#   3. generate backend/frontend .dev.vars from the current environment
#   4. start both local Workers
#   5. run lightweight smoke checks through both Workers
#
# Required, unless already present in backend/script/config/.dev.vars:
#   OPENAI_API_KEY
#   ADMIN_TOKEN
#
# Optional:
#   BACKEND_PORT=8787
#   FRONTEND_PORT=8788
#   FRONTEND_PASSWORD=...
#   SESSION_SECRET=...
#   KEEP_ALIVE=false          # stop after smoke checks
#   RUN_FULL_API_TESTS=true   # also run backend/script/test.sh and frontend/script/test.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_VARS="$ROOT/backend/script/config/.dev.vars"
FRONTEND_VARS="$ROOT/frontend/script/config/.dev.vars"
BACKEND_CONFIG="$ROOT/backend/wrangler.toml"
FRONTEND_CONFIG="$ROOT/frontend/wrangler.toml"

BACKEND_PORT="${BACKEND_PORT:-8787}"
FRONTEND_PORT="${FRONTEND_PORT:-8788}"
BACKEND_BASE_URL="http://127.0.0.1:${BACKEND_PORT}"
FRONTEND_BASE_URL="http://127.0.0.1:${FRONTEND_PORT}"
KEEP_ALIVE="${KEEP_ALIVE:-true}"
RUN_FULL_API_TESTS="${RUN_FULL_API_TESTS:-false}"
APP_TITLE="${APP_TITLE:-PaperSniffer}"

BACKEND_PID=""
FRONTEND_PID=""
WORKER_PID=""
LOG_DIR="$(mktemp -d)"
COOKIE_JAR="$(mktemp)"

usage() {
  cat >&2 <<'EOF'
Usage:
  OPENAI_API_KEY=sk-... ADMIN_TOKEN=... npm run local:build-run

Environment knobs:
  BACKEND_PORT=8787
  FRONTEND_PORT=8788
  FRONTEND_PASSWORD=<optional UI password>
  SESSION_SECRET=<optional cookie signing secret>
  KEEP_ALIVE=true|false
  RUN_FULL_API_TESTS=true|false
EOF
  exit 1
}

load_existing_vars() {
  if [[ -f "$BACKEND_VARS" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$BACKEND_VARS"
    set +a
  fi

  if [[ -f "$FRONTEND_VARS" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$FRONTEND_VARS"
    set +a
  fi
}

require_tools() {
  local missing=()
  for tool in npm npx curl; do
    if ! command -v "$tool" >/dev/null 2>&1; then
      missing+=("$tool")
    fi
  done

  if (( ${#missing[@]} > 0 )); then
    echo "Error: missing required command(s): ${missing[*]}" >&2
    exit 1
  fi
}

require_env_vars() {
  local missing=()

  for key in OPENAI_API_KEY ADMIN_TOKEN; do
    if [[ -z "${!key+x}" ]] || [[ -z "${!key}" ]]; then
      missing+=("$key")
    fi
  done

  if (( ${#missing[@]} > 0 )); then
    echo "Error: missing required environment variable(s): ${missing[*]}" >&2
    usage
  fi
}

write_var_line() {
  local key="$1"
  local value="$2"
  local file="$3"

  if [[ "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
    echo "Error: $key contains a newline; pass it as a single-line value." >&2
    exit 1
  fi

  if [[ "$value" =~ [[:space:]#] ]]; then
    local escaped="$value"
    escaped="${escaped//\\/\\\\}"
    escaped="${escaped//\"/\\\"}"
    printf '%s="%s"\n' "$key" "$escaped" >> "$file"
  else
    printf '%s=%s\n' "$key" "$value" >> "$file"
  fi
}

write_dev_vars() {
  mkdir -p "$(dirname "$BACKEND_VARS")" "$(dirname "$FRONTEND_VARS")"

  {
    echo "# Generated by script/local-build-run.sh."
    echo "# Do not edit this file manually; rerun the script with updated environment variables."
  } > "$BACKEND_VARS"
  write_var_line OPENAI_API_KEY "$OPENAI_API_KEY" "$BACKEND_VARS"
  write_var_line ADMIN_TOKEN "$ADMIN_TOKEN" "$BACKEND_VARS"

  {
    echo "# Generated by script/local-build-run.sh."
    echo "# Do not edit this file manually; rerun the script with updated environment variables."
  } > "$FRONTEND_VARS"
  write_var_line BACKEND_BASE_URL "$BACKEND_BASE_URL" "$FRONTEND_VARS"
  write_var_line BACKEND_ADMIN_TOKEN "$ADMIN_TOKEN" "$FRONTEND_VARS"
  write_var_line APP_TITLE "$APP_TITLE" "$FRONTEND_VARS"

  if [[ -n "${FRONTEND_PASSWORD:-}" ]]; then
    write_var_line FRONTEND_PASSWORD "$FRONTEND_PASSWORD" "$FRONTEND_VARS"
  fi

  if [[ -n "${SESSION_SECRET:-}" ]]; then
    write_var_line SESSION_SECRET "$SESSION_SECRET" "$FRONTEND_VARS"
  fi

  echo "==> Wrote backend env: $BACKEND_VARS"
  echo "==> Wrote frontend env: $FRONTEND_VARS"
}

cleanup() {
  local exit_code=$?

  if [[ -n "$FRONTEND_PID" ]] && kill -0 "$FRONTEND_PID" >/dev/null 2>&1; then
    kill "$FRONTEND_PID" >/dev/null 2>&1 || true
  fi

  if [[ -n "$BACKEND_PID" ]] && kill -0 "$BACKEND_PID" >/dev/null 2>&1; then
    kill "$BACKEND_PID" >/dev/null 2>&1 || true
  fi

  rm -rf "$LOG_DIR" "$COOKIE_JAR"
  exit "$exit_code"
}

show_log_tail() {
  local name="$1"
  local file="$2"

  echo "---- $name log tail ----" >&2
  if [[ -s "$file" ]]; then
    tail -n 80 "$file" >&2
  else
    echo "<empty>" >&2
  fi
  echo "------------------------" >&2
}

start_worker() {
  local name="$1"
  local log_file="$2"
  shift 2

  echo "==> Starting $name Worker"
  "$@" > "$log_file" 2>&1 &
  WORKER_PID="$!"
}

wait_for_backend() {
  echo "==> Waiting for backend at $BACKEND_BASE_URL"

  for _ in $(seq 1 90); do
    local status
    status="$(
      curl --silent --show-error \
        --connect-timeout 2 \
        --max-time 5 \
        --output /dev/null \
        --write-out "%{http_code}" \
        --header "Authorization: Bearer $ADMIN_TOKEN" \
        "$BACKEND_BASE_URL/health" \
        2>/dev/null || true
    )"

    if [[ "$status" == "200" ]]; then
      echo "==> Backend is ready"
      return
    fi

    if ! kill -0 "$BACKEND_PID" >/dev/null 2>&1; then
      show_log_tail "backend" "$LOG_DIR/backend.log"
      echo "Error: backend Worker exited before becoming ready." >&2
      exit 1
    fi

    sleep 1
  done

  show_log_tail "backend" "$LOG_DIR/backend.log"
  echo "Error: backend did not become ready in time." >&2
  exit 1
}

wait_for_frontend() {
  echo "==> Waiting for frontend at $FRONTEND_BASE_URL"

  local path="/status"
  local expected="200"
  if [[ -n "${FRONTEND_PASSWORD:-}" ]]; then
    path="/login"
  fi

  for _ in $(seq 1 90); do
    local status
    status="$(
      curl --silent --show-error \
        --connect-timeout 2 \
        --max-time 5 \
        --output /dev/null \
        --write-out "%{http_code}" \
        "$FRONTEND_BASE_URL$path" \
        2>/dev/null || true
    )"

    if [[ "$status" == "$expected" ]]; then
      echo "==> Frontend is ready"
      return
    fi

    if ! kill -0 "$FRONTEND_PID" >/dev/null 2>&1; then
      show_log_tail "frontend" "$LOG_DIR/frontend.log"
      echo "Error: frontend Worker exited before becoming ready." >&2
      exit 1
    fi

    sleep 1
  done

  show_log_tail "frontend" "$LOG_DIR/frontend.log"
  echo "Error: frontend did not become ready in time." >&2
  exit 1
}

assert_http() {
  local name="$1"
  local expected="$2"
  shift 2

  local output
  output="$(mktemp)"
  local status
  status="$(
    curl --silent --show-error \
      --connect-timeout 5 \
      --max-time 30 \
      --output "$output" \
      --write-out "%{http_code}" \
      "$@" \
      2>/dev/null || true
  )"

  if [[ "$status" != "$expected" ]]; then
    echo "FAIL $name: expected HTTP $expected, got ${status:-<none>}" >&2
    sed 's/^/  /' "$output" >&2 || true
    rm -f "$output"
    exit 1
  fi

  rm -f "$output"
  echo "PASS $name -> $status"
}

login_frontend_if_needed() {
  if [[ -z "${FRONTEND_PASSWORD:-}" ]]; then
    return
  fi

  assert_http \
    "frontend login" \
    "303" \
    --request POST \
    --cookie-jar "$COOKIE_JAR" \
    --data-urlencode "password=$FRONTEND_PASSWORD" \
    "$FRONTEND_BASE_URL/login"
}

run_light_smoke_tests() {
  echo "==> Running lightweight smoke checks"

  assert_http \
    "backend health" \
    "200" \
    --header "Authorization: Bearer $ADMIN_TOKEN" \
    "$BACKEND_BASE_URL/health"

  assert_http \
    "backend config" \
    "200" \
    --header "Authorization: Bearer $ADMIN_TOKEN" \
    "$BACKEND_BASE_URL/api/config"

  login_frontend_if_needed

  local cookie_args=()
  if [[ -n "${FRONTEND_PASSWORD:-}" ]]; then
    cookie_args=(--cookie "$COOKIE_JAR")
  fi

  assert_http "frontend status page" "200" "${cookie_args[@]}" "$FRONTEND_BASE_URL/status"
  assert_http "frontend dashboard page" "200" "${cookie_args[@]}" "$FRONTEND_BASE_URL/"
  assert_http "frontend API proxy health" "200" "${cookie_args[@]}" "$FRONTEND_BASE_URL/api/health"
}

run_full_api_tests_if_requested() {
  if [[ "$RUN_FULL_API_TESTS" != "true" ]]; then
    return
  fi

  echo "==> Running full API smoke tests"
  bash "$ROOT/backend/script/test.sh" local "$BACKEND_BASE_URL"
  bash "$ROOT/frontend/script/test.sh" local "$FRONTEND_BASE_URL"
}

load_existing_vars
require_tools
require_env_vars

trap cleanup EXIT INT TERM

cd "$ROOT"

echo "==> Typechecking backend and frontend"
npm run typecheck

echo "==> Building backend and frontend"
npm run build

write_dev_vars

start_worker \
  "backend" \
  "$LOG_DIR/backend.log" \
  npx wrangler dev \
    --config "$BACKEND_CONFIG" \
    --local \
    --env-file "$BACKEND_VARS" \
    --port "$BACKEND_PORT"
BACKEND_PID="$WORKER_PID"
wait_for_backend

start_worker \
  "frontend" \
  "$LOG_DIR/frontend.log" \
  npx wrangler dev \
    --config "$FRONTEND_CONFIG" \
    --local \
    --env-file "$FRONTEND_VARS" \
    --port "$FRONTEND_PORT"
FRONTEND_PID="$WORKER_PID"
wait_for_frontend

run_light_smoke_tests
run_full_api_tests_if_requested

echo "==> Local build-run pass completed"
echo "    Backend:  $BACKEND_BASE_URL"
echo "    Frontend: $FRONTEND_BASE_URL"

if [[ "$KEEP_ALIVE" != "true" ]]; then
  echo "==> KEEP_ALIVE=false, stopping local Workers"
  exit 0
fi

echo "==> Workers are still running. Press Ctrl+C to stop both."
wait "$BACKEND_PID" "$FRONTEND_PID"
